// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SQuiz.Infrastructure.Data;

#nullable disable

namespace SQuiz.Infrastructure.Data.Migrations
{
    [DbContext(typeof(SQuizContext))]
    partial class SQuizContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.HasSequence<int>("QuizModerator_shortId_seq");

            modelBuilder.HasSequence<int>("Quizzes_shortId_seq");

            modelBuilder.Entity("SQuiz.Shared.Models.Answer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(36)");

                    b.Property<string>("AnswerText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("QuestionId")
                        .IsRequired()
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("SQuiz.Shared.Models.Question", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(36)");

                    b.Property<int>("AnsweringTime")
                        .HasColumnType("int");

                    b.Property<string>("CorrectAnswerId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("QuizId")
                        .IsRequired()
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CorrectAnswerId")
                        .IsUnique()
                        .HasFilter("[CorrectAnswerId] IS NOT NULL");

                    b.HasIndex("QuizId");

                    b.ToTable("Questiones");
                });

            modelBuilder.Entity("SQuiz.Shared.Models.Quiz", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(36)");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset?>("DateCreated")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DateUpdated")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ShortId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("NEXT VALUE FOR Quizzes_shortId_seq");

                    b.HasKey("Id");

                    b.HasIndex("ShortId");

                    b.ToTable("Quizzes");
                });

            modelBuilder.Entity("SQuiz.Shared.Models.QuizModerator", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset?>("DateCreated")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DateUpdated")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("QuizId")
                        .IsRequired()
                        .HasColumnType("char(36)");

                    b.Property<int>("ShortId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.ToTable("QuizModerator");
                });

            modelBuilder.Entity("SQuiz.Shared.Models.Answer", b =>
                {
                    b.HasOne("SQuiz.Shared.Models.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("SQuiz.Shared.Models.Question", b =>
                {
                    b.HasOne("SQuiz.Shared.Models.Answer", "CorrectAnswer")
                        .WithOne()
                        .HasForeignKey("SQuiz.Shared.Models.Question", "CorrectAnswerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SQuiz.Shared.Models.Quiz", "Quiz")
                        .WithMany("Questions")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CorrectAnswer");

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("SQuiz.Shared.Models.QuizModerator", b =>
                {
                    b.HasOne("SQuiz.Shared.Models.Quiz", "Quiz")
                        .WithMany("QuizModerators")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("SQuiz.Shared.Models.Question", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("SQuiz.Shared.Models.Quiz", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("QuizModerators");
                });
#pragma warning restore 612, 618
        }
    }
}
